config/routes.rb
Facefind::Application.routes.draw do |map|
  
  # Find profile route
  match '/find(.:format)/(:id)' => "profiles#find", :id => /.+/, :as => :find
  
  # Search route
  match '/search' => "profiles#search", :as => :search
  
  # About route
  match '/about' => "profiles#about", :as => :about
  
  # Root route
  root :to => "profiles#index"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  # Make sure facebook id is present, unique and a number
  validates :facebook_id, :presence => true, :uniqueness => true, :numericality => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  respond_to :html, :json, :only => :find
  
  # Count profiles in all actions, except search
  before_filter :count_profiles, :except => :search
  
  # Cache index and about actions
  caches_action :index, :about
  
  def index
  end
  
  def about
  end

  def search
    # Redirect to root path unless id exists
    redirect_to root_path and return unless params[:id]
    
    # Redirect to find action to show data
    redirect_to find_path(:id => params[:id])
  end
  
  def find
    # Redirect to root path unless id exists
    redirect_to root_path and return unless params[:id]
    
    # Find Facebook if from url (id param) by using regexes
    profile_id = case params[:id]
    when /[a-z\/:\.-]+\.fbcdn\.net\/[\w\/\-]+\/\w(\d+)_[\d\_]+.jpg\z/ then "#{$1}"
    when /[a-z\/:\.-]+\.fbcdn\.net\/[\w\/\-\.]+\/\d*_?\d+_(\d+)_\d+_[\d_]*\w.jpg\z/ then "#{$1}"
    when /[a-z\/:\.]*\.facebook\.com\/[\w\W]+\.php\?pid=\d+&id=(\d+)(&fbid=\d+)?\z/ then "#{$1}"
    
    # No matches, show error
    else
      handle_error('Wrong format or not a Facebook picture!') and return
    end
    
    # Parse Facebook Graph API with profile id
    uri = URI.parse('http://graph.facebook.com/' + profile_id)
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    
    # Decode old JSON response as hash
    @result = ActiveSupport::JSON.decode(response.body)
    
    # Redirect to error page if invalid ID or none found
    handle_error('Nothing found!') and return unless @result.respond_to?(:has_key?) and @result.has_key?("name")
    
    # Add Facebook link if not included in data fetched from API
    @result["link"] ||= profile_link_for(@result["id"])
    
    @profile = Profile.find_or_create_by_facebook_id(:facebook_id => @result['id'])
    
    # Respond!
    respond_with(@result)
    
    # Expire caches
    expire_action :action => :index
    expire_action :action => :about
  end
  
  private
  
  # Return link to Facebook profile based on id
  def profile_link_for(id)
    "http://facebook.com/profile.php?id=" + id
  end
  
  # Handle error based on requested format
  def handle_error(message)
    respond_to do |format|
      
      # HTML: Redirect to root with 404 and flash notice
      format.html { redirect_to home_path, :state => :not_found, :notice => message }
      
      # JSON: 404 and blank file
      format.json { render :json => message, :status => :not_found }
    end
  end
  
  # Count total profiles stored
  def count_profiles
    @total_profiles = Profile.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notice
    if flash[:notice]
      content_tag :span, flash[:notice], :class => "error"
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>facefind!</title>
  <%= stylesheet_link_tag :all, :recursive => true, :cache => "all" %>
  <%= javascript_include_tag 'jquery.js', 'application.js', :cache => "all" %>
  <%= csrf_meta_tag %>
</head>
<body id="<%= action_name %>">
	
	<h1><%= link_to "facefind", root_path %></h1>

	<div id="wrapper">
		<ul id="nav">
			<li><%= link_to 'home', root_path, :id => "index" %></li>
			<li><%= link_to 'about', about_path, :id => "about" %></li>
		</ul>

		<%= yield %>
	</div>

	<p id="footer">Some data is saved for statistic purposes. Served <%= @total_profiles %> Facebook profiles so far.</p>

</body>
</html>

app/views/profiles/_search_form.html.erb
<h3 id="guide">Enter your Facebook picture URL in the field below:</h3>

<%= form_tag(search_path, :method => "get", :id => "faceform") do %>
	<%= text_field_tag(:id, params[:id]) %>
	<%= submit_tag 'Find its face!', :id => "submit" %>
<% end -%>

app/views/profiles/about.html.erb
<p>Have you ever had the link to a Facebook picture without knowing who the owner is? Now you can find out! Facefind is a free service that eats any Facebook picture url and spits out the name and profile picture of its owner.</p>

<p>How is it possible, you say? Well, it's really simple: Our team of top trained baby penguins receive your picture url, and with the help of &frac34; magic and &frac14; skills, they extract the Facebook ID of the owner from the picture. Then they call the Facebook User Information Hotline to get the owners name and profile picture, which is finally served back to you.</p>

app/views/profiles/find.html.erb
<%= render "search_form" %>

<div id="results">
	<h2 id="name"><%= link_to @result['name'], @result['link'] unless flash_notice %></h2>
	<div id="picture"><%= link_to image_tag('http://graph.facebook.com/' + @result['id'] + '/picture?type=large'), @result['link'] %></div>
	<p id="link"><%= link_to 'Direct link to this result!', find_url(:id => params[:id] )%></p>
</div>

app/views/profiles/find.json.erb
<%= raw @result.to_json %>

app/views/profiles/index.html.erb
<%= render "search_form" %>

<div id="results">		
	<h2 id="name"><%= flash_notice %></h2>
	<div id="picture"></div>
	<p id="link"></p>
</div>